### ISSUE TITLE
click: higher version should be required for pip install

### ISSUE THREAD

**Issue by bpinsard** [nimh-comppsych/fmriprep-group-report#5]
got the following error after `pip install fmriprep-group-report` in a virtualenv with other packages installed.
```
Traceback (most recent call last):                                                                                                                        
  File "/lustre03/project/6003287/bpinsard/.virtualenvs/neuromod_data/bin/fmriprepgr", line 8, in <module>                                                
    sys.exit(make_report())                                                                                                                               
  File "/lustre03/project/6003287/bpinsard/.virtualenvs/neuromod_data/lib/python3.8/site-packages/click/core.py", line 829, in __call__                   
    return self.main(*args, **kwargs)                                                                                                                     
  File "/lustre03/project/6003287/bpinsard/.virtualenvs/neuromod_data/lib/python3.8/site-packages/click/core.py", line 781, in main                       
    with self.make_context(prog_name, args, **extra) as ctx:                                                                                              
  File "/lustre03/project/6003287/bpinsard/.virtualenvs/neuromod_data/lib/python3.8/site-packages/click/core.py", line 700, in make_context               
    self.parse_args(ctx, args)                                                                                                                            
  File "/lustre03/project/6003287/bpinsard/.virtualenvs/neuromod_data/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args                
    value, args = param.handle_parse_result(ctx, opts, args)                                                                                              
  File "/lustre03/project/6003287/bpinsard/.virtualenvs/neuromod_data/lib/python3.8/site-packages/click/core.py", line 1623, in handle_parse_result       
    value = self.full_process_value(ctx, value)                              
  File "/lustre03/project/6003287/bpinsard/.virtualenvs/neuromod_data/lib/python3.8/site-packages/click/core.py", line 1965, in full_process_value        
    return Parameter.full_process_value(self, ctx, value)
  File "/lustre03/project/6003287/bpinsard/.virtualenvs/neuromod_data/lib/python3.8/site-packages/click/core.py", line 1589, in full_process_value        
    value = self.process_value(ctx, value)                                                                                                                
  File "/lustre03/project/6003287/bpinsard/.virtualenvs/neuromod_data/lib/python3.8/site-packages/click/core.py", line 1579, in process_value             
    return self.type_cast_value(ctx, value)                                  
  File "/lustre03/project/6003287/bpinsard/.virtualenvs/neuromod_data/lib/python3.8/site-packages/click/core.py", line 1554, in type_cast_value           
    raise TypeError(                                                         
TypeError: Attempted to invoke composite type but nargs has been set to 0. This is not supported; nargs needs to be set to a fixed value > 1.  
``` 

Turns out the requirements didn't upgrade the already installed click packages (7.1.2) 
`pip install --upgrade click` seems to have fixed the error by getting click-8.1.3.

**Comment by Shotgunosine** [comment]
Thanks! This should be fixed now.
